routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::post('/registrar', 'UsersController@register')->name('user.register');

Route::group(['prefix' => 'sistema', 'as' => 'sistema.','middleware' => 'auth'], function () {

    //EMPRESA
    Route::get('/minha-empresa', ['as' => 'empresas.edit','uses' =>'EmpresasController@edit']);
    Route::put('/editar-cadastro', ['as' => 'empresas.update','uses' =>'EmpresasController@update']);

    //CATEGORIAS
    Route::get('/categorias','CategoriasController@show')->name('categoria.show');
    Route::post('/nova-categoria', 'CategoriasController@store')->name('categoria.store');
    Route::get('/mudar-status-categoria/{id}/{status}','CategoriasController@changeStatus')->name('categoria.change');
    Route::get('/remover-categoria/{id}/','CategoriasController@softDelete')->name('categoria.delete');

    //CLIENTES
    Route::get('/clientes', ['as' => 'clientes.showAll','uses' =>'ClientesController@showAll']);
    Route::get('/novo-cliente', ['as' => 'clientes.create','uses' =>'ClientesController@create']);
    Route::post('/cadastrar-cliente', ['as' => 'clientes.store','uses' =>'ClientesController@store']);
    Route::get('/editar-cliente/{id}', ['as' => 'clientes.edit','uses' =>'ClientesController@edit']);
    Route::put('/editar-cadastro-cliente/{id}', ['as' => 'clientes.update','uses' =>'ClientesController@update']);

    //FORMAS DE PAGAMENTO
    Route::get('/formas-de-pagamento','FormasPagamentoController@show')->name('formas.show');
    Route::post('/nova-formas-de-pagamento', 'FormasPagamentoController@store')->name('formas.store');
    Route::get('/mudar-status-formas-de-pagamento/{id}/{status}','FormasPagamentoController@changeStatus')->name('formas.change');

    //PEDIDO
    Route::get('/novo-pedido','PedidosController@create')->name('pedido.create');
    Route::post('/adicionar-item-pedido', 'PedidosController@addToCart')->name('pedido.addItem');
    Route::post('/salvar-pedido', 'PedidosController@store')->name('pedido.store');
    Route::post('/remover-item-pedido', 'PedidosController@removeItemPedido')->name('carrinho.remove');
    Route::get('/pedidos', 'PedidosController@showAll')->name('pedido.showAll');

    //PRODUTOS
    Route::get('/produtos','ProdutosController@showAll')->name('produto.showAll');
    Route::get('/novo-produto', 'ProdutosController@create')->name('produto.create');
    Route::post('/cadastrar-produto', 'ProdutosController@store')->name('produto.store');
    Route::get('/editar-produto/{id}','ProdutosController@edit')->name('produto.edit');
    Route::put('/editar-cadastro-produto/{id}','ProdutosController@update')->name('produto.update');
    Route::post('/ajax-busca-produto-por-categoria','ProdutosController@findProdutosPorCategoriaAjax');

});

app/Models/Produto.php
<?php

namespace Tcc\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use Tcc\Scopes\TenantGlobalScope;
use Tcc\Scopes\TenantModelsScope;

class Produto extends Model implements Transformable
{
    use TransformableTrait, TenantModelsScope, SoftDeletes;

    protected $fillable = ['produto', 'descricao', 'categoria_id', 'empresa_id', 'preco', 'ativo'];


    public function empresa()
    {
        return $this->belongsTo(Empresa::class);
    }

    public function categoria()
    {
        return $this->belongsTo(Categoria::class)->withTrashed();
    }

    public function setPrecoAttribute($preco)
    {
        $this->attributes['preco'] = $preco;
    }

    public function getPrecoAttribute()
    {
        return $this->attributes['preco'];
    }

}

app/Http/Controllers/Api/ProdutosController.php
<?php

namespace Tcc\Http\Controllers\Api;

use Illuminate\Http\Request;
use Tcc\Criteria\FiltroPorEmpresaCriteria;
use Tcc\Http\Controllers\Controller;
use Tcc\Repositories\ProdutoRepository;

class ProdutosController extends Controller
{
    /** @var  ProdutoRepository */
    protected $repository;

    /**
     * ProdutosController constructor.
     * @param ProdutoRepository $repository
     */
    public function __construct(ProdutoRepository $repository)
    {
        $this->repository = $repository;
    }


    public function index()
    {
        $this->repository->pushCriteria(FiltroPorEmpresaCriteria::class);
        $produtos = $this->repository->all();

        return response()->json($produtos);
    }


}

app/Http/Controllers/ProdutosController.php
<?php

namespace Tcc\Http\Controllers;

use Illuminate\Http\Request;
use Prettus\Validator\Exceptions\ValidatorException;
use Tcc\Http\Requests\ProdutoCreateRequest;
use Tcc\Http\Requests\ProdutoUpdateRequest;
use Tcc\Repositories\CategoriaRepository;
use Tcc\Repositories\ProdutoRepository;

class ProdutosController extends Controller
{
    /** @var  ProdutoRepository */
    protected $repository;

    /** @var  CategoriaRepository */
    protected $categoriaRepository;

    /**
     * ProdutosController constructor.
     * @param ProdutoRepository $repository
     * @param CategoriaRepository $categoriaRepository
     */
    public function __construct(ProdutoRepository $repository, CategoriaRepository $categoriaRepository)
    {
        $this->repository = $repository;
        $this->categoriaRepository = $categoriaRepository;
    }


    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $categorias = $this->categoriaRepository->listarTodasCategoriasForm();

        return view('produtos.create', compact('categorias'));
    }


    /**
     * @param  ProdutoCreateRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProdutoCreateRequest $request)
    {
        try {
            $request->request->add(['user_id' => auth()->user()->id]);
            $this->repository->create($request->all());
            flash()->success('Empresa Cadastrado Com Sucesso');

            return redirect()->back();

        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error' => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\JsonResponse|\Illuminate\View\View
     */
    public function showAll()
    {
        $produtos = $this->repository->with('categoria')->paginate(15);

        return view('produtos.showAll', compact('produtos'));
    }


    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $produto = $this->repository->find($id);
        $categorias = $this->categoriaRepository->listarTodasCategoriasForm();

        return view('produtos.edit', compact('produto', 'categorias'));
    }

    /**
     * @param ProdutoUpdateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ProdutoUpdateRequest $request, $id)
    {
        try {
            $this->repository->update($request->all(), $id);

            flash()->success('Os dados do produto foram alterados com sucesso.');

            return back();
        } catch (ValidatorException $e) {
            flash()->error($e->getMessageBag());

            return back();
        }
    }

    /**
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Produto apagado.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Produto removida.');
    }

    /**
     * @param Request $request
     * @return array
     */
    public function findProdutosPorCategoriaAjax(Request $request)
    {
        $produtos = [];
        if (isset($request->categoria) && !empty($request->categoria)) {
            $produtos = $this->repository->buscaProdutosPorCategoriaForm($request->categoria);
        }

        return response()->json($produtos);
    }


}

resources/views/produtos/_form.blade.php
<div class="col-md-6 form-group{{ $errors->has('produto') ? 'has-error' : '' }}">
    <label for="name" class="">Produto</label>
    {!! Form::text('produto',null,['class' => 'form-control','required']) !!}
    @if ($errors->has('produto'))
        <span class="help-block">
          <strong>{{ $errors->first('produto') }}</strong>
        </span>
    @endif
</div>

<div class="col-md-2 form-group{{ $errors->has('preco') ? 'has-error' : '' }}">
    <label for="name" class="">Preço</label>
    {!! Form::text('preco',null,['class' => 'form-control','required']) !!}
    @if ($errors->has('preco'))
        <span class="help-block">
            <strong>{{ $errors->first('preco') }}</strong>
        </span>
    @endif
</div>

<div class="col-md-4 form-group{{ $errors->has('categoria_id') ? 'has-error' : '' }}">
    <label for="name" class="">Categoria</label>
    {!! Form::select('categoria_id',[null => 'SELECIONE UMA CATEGORIA']+$categorias->toArray(),null,
       ['class' => 'form-control', 'required']) !!}
    @if ($errors->has('categoria_id'))
        <span class="help-block">
            <strong>{{ $errors->first('categoria_id') }}</strong>
        </span>
    @endif
</div>

<div class="col-md-12 form-group{{ $errors->has('descricao') ? ' has-error' : '' }}">
    <label for="name" class="">Descrição</label>
    {!! Form::textarea('descricao',null,['class' => 'form-control','required']) !!}
    @if ($errors->has('descricao'))
        <span class="help-block">
            <strong>{{ $errors->first('descricao') }}</strong>
         </span>
    @endif
</div>

<div class="col-md-6 form-group{{ $errors->has('ativo') ? ' has-error' : '' }}">
    <label>Ativar?</label>
    <label class="radio-inline">
        {!! Form::radio('ativo', '1', true) !!} Sim
    </label>
    <label class="radio-inline">
        {!! Form::radio('ativo', '0', false) !!} Não
    </label>
    @if ($errors->has('ativo'))
        <span class="help-block">
            <strong>{{ $errors->first('ativo') }}</strong>
        </span>
    @endif
</div>

resources/views/produtos/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="panel panel-default">
                    <div class="panel-heading">Formulário de Cadastro de Produto</div>
                    <div class="panel-body">
                        @include('errors._check_form')
                        @include('flash::message')
                        {!! Form::open(['route' => 'sistema.produto.store', 'method' => 'post' ]) !!}

                        @include('produtos._form')

                        <div class="form-group">
                            <div class="col-md-4 col-md-offset-4">
                                <button type="submit" class="btn btn-success">
                                    Cadastrar
                                </button>
                                <button type="reset" class="btn btn-warning">
                                    Limpar Cadastro
                                </button>
                            </div>
                        </div>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/produtos/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="panel panel-default">
                    <div class="panel-heading">Edição de Cadastro de Empresa</div>
                    <div class="panel-body">
                        @include('errors._check_form')
                        @include('flash::message')

                        {!! Form::model($produto,['route' => ['sistema.produto.update',$produto->id], 'method' => 'put']) !!}

                        @include('produtos._form')

                        <div class="form-group">
                            <div class="col-md-4 col-md-offset-4">
                                <button type="submit" class="btn btn-success">
                                    Salvar Alterações
                                </button>
                                <a href="{{route('sistema.produto.showAll')}}" class="btn btn-info">
                                    Voltar
                                </a>
                            </div>
                        </div>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/produtos/showAll.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="panel panel-default">
                    <div class="panel-heading">Produtos Cadastrados</div>
                    <div class="panel-body">
                        @include('errors._check_form')
                        @include('flash::message')
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Produto</th>
                                <th>Categoria</th>
                                <th>Preço</th>
                                <th>Ativo</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($produtos as $produto)
                                <tr>
                                    <td>{{$produto->id}}</td>
                                    <td>{{$produto->produto}}</td>
                                    <td>{{$produto->categoria->categoria}}</td>
                                    <td>R$ {{$produto->preco}}</td>
                                    <td>{{($produto->ativo)? 'sim':'não'}}</td>
                                    <td>
                                        <a href="{{route('sistema.produto.edit',[$produto->id])}}"
                                           class="btn btn-primary btn-sm">
                                            Editar
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {!! $produtos->links() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection