routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::post('/registrar', 'UsersController@register')->name('user.register');

Route::group(['prefix' => 'sistema', 'as' => 'sistema.','middleware' => 'auth'], function () {

    //EMPRESA
    Route::get('/minha-empresa', ['as' => 'empresas.edit','uses' =>'EmpresasController@edit']);
    Route::put('/editar-cadastro', ['as' => 'empresas.update','uses' =>'EmpresasController@update']);

    //CATEGORIAS
    Route::get('/categorias','CategoriasController@show')->name('categoria.show');
    Route::post('/nova-categoria', 'CategoriasController@store')->name('categoria.store');
    Route::get('/mudar-status-categoria/{id}/{status}','CategoriasController@changeStatus')->name('categoria.change');
    Route::get('/remover-categoria/{id}/','CategoriasController@softDelete')->name('categoria.delete');

    //CLIENTES
    Route::get('/clientes', ['as' => 'clientes.showAll','uses' =>'ClientesController@showAll']);
    Route::get('/novo-cliente', ['as' => 'clientes.create','uses' =>'ClientesController@create']);
    Route::post('/cadastrar-cliente', ['as' => 'clientes.store','uses' =>'ClientesController@store']);
    Route::get('/editar-cliente/{id}', ['as' => 'clientes.edit','uses' =>'ClientesController@edit']);
    Route::put('/editar-cadastro-cliente/{id}', ['as' => 'clientes.update','uses' =>'ClientesController@update']);

    //FORMAS DE PAGAMENTO
    Route::get('/formas-de-pagamento','FormasPagamentoController@show')->name('formas.show');
    Route::post('/nova-formas-de-pagamento', 'FormasPagamentoController@store')->name('formas.store');
    Route::get('/mudar-status-formas-de-pagamento/{id}/{status}','FormasPagamentoController@changeStatus')->name('formas.change');

    //PEDIDO
    Route::get('/novo-pedido','PedidosController@create')->name('pedido.create');
    Route::post('/adicionar-item-pedido', 'PedidosController@addToCart')->name('pedido.addItem');
    Route::post('/salvar-pedido', 'PedidosController@store')->name('pedido.store');
    Route::post('/remover-item-pedido', 'PedidosController@removeItemPedido')->name('carrinho.remove');
    Route::get('/pedidos', 'PedidosController@showAll')->name('pedido.showAll');

    //PRODUTOS
    Route::get('/produtos','ProdutosController@showAll')->name('produto.showAll');
    Route::get('/novo-produto', 'ProdutosController@create')->name('produto.create');
    Route::post('/cadastrar-produto', 'ProdutosController@store')->name('produto.store');
    Route::get('/editar-produto/{id}','ProdutosController@edit')->name('produto.edit');
    Route::put('/editar-cadastro-produto/{id}','ProdutosController@update')->name('produto.update');
    Route::post('/ajax-busca-produto-por-categoria','ProdutosController@findProdutosPorCategoriaAjax');

});

app/Http/Controllers/FormasPagamentoController.php
<?php

namespace Tcc\Http\Controllers;

use Tcc\Http\Requests\FormaPagamentoCreateRequest;
use Tcc\Repositories\EmpresaRepository;
use Tcc\Repositories\FormaPagamentoRepository;

class FormasPagamentoController extends Controller
{

    /** @var  FormaPagamentoRepository */
    protected $repository;


    /**
     * FormasPagamentoController constructor.
     * @param FormaPagamentoRepository $repository
     */
    public function __construct(FormaPagamentoRepository $repository)
    {
        $this->repository = $repository;
    }

    public function show()
    {
        $formasDePagamento = $this->repository->all();

        return view('formasPagamentos.show', compact('formasDePagamento'));
    }


    /**
     * @param FormaPagamentoCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(FormaPagamentoCreateRequest $request)
    {
        $this->repository->create($request->all());
        flash()->success('Forma de Pagamento Cadastrada com sucesso.');

        return redirect()->action('FormasPagamentoController@show');
    }


    public function changeStatus($id, $status){
        $this->repository->update(['ativo' => $status],$id);
        flash()->success('Forma de Pagamento Alterada com sucesso.');

        return redirect()->action('FormasPagamentoController@show');
    }

}

resources/views/formasPagamentos/_form.blade.php
<div class="col-md-8 form-group{{ $errors->has('forma_pagamento') ? ' has-error' : '' }}">
    <label for="name" class="">Forma de Pagamento</label>
    {!! Form::text('forma_pagamento',null,['class' => 'form-control','required']) !!}
</div>

resources/views/formasPagamentos/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="panel panel-default">
                    <div class="panel-heading">Nova Forma de Pagamento</div>
                    <div class="panel-body">
                        @include('errors._check_form')
                        @include('flash::message')
                        {!! Form::open(['route' => 'sistema.formas.store', 'method' => 'post' ]) !!}

                        @include('formasPagamentos._form')

                        <div class="form-group">
                            <div class="col-md-4 col-md-offset-4">
                                <button type="submit" class="btn btn-success">
                                    Cadastrar
                                </button>
                                <button type="reset" class="btn btn-warning">
                                    Limpar Cadastro
                                </button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 ">
                <div class="panel panel-default">
                    <div class="panel-heading">Formas de Pagamento Cadastradas</div>
                    <div class="panel-body">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Forma de Pagamento</th>
                                <th>Ativo</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($formasDePagamento as $forma)
                                <tr>
                                    <td>{{$forma->id}}</td>
                                    <td>{{$forma->forma_pagamento}}</td>
                                    <td>{{($forma->ativo)? 'Sim': 'Não'}}</td>
                                    <td>
                                        @if($forma->ativo == 0)
                                            <a href="{{route('sistema.formas.change',[$forma->id,1])}}"
                                               class="btn btn-success btn-sm">
                                                Ativar
                                            </a>
                                        @else
                                            <a href="{{route('sistema.formas.change',[$forma->id,0])}}"
                                               class="btn btn-warning btn-sm">
                                                Desativar
                                            </a>
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <tr class="text-center">
                                    <td colspan="4">Nenhum registro encontrado.</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection