routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::post('/registrar', 'UsersController@register')->name('user.register');

Route::group(['prefix' => 'sistema', 'as' => 'sistema.','middleware' => 'auth'], function () {

    //EMPRESA
    Route::get('/minha-empresa', ['as' => 'empresas.edit','uses' =>'EmpresasController@edit']);
    Route::put('/editar-cadastro', ['as' => 'empresas.update','uses' =>'EmpresasController@update']);

    //CATEGORIAS
    Route::get('/categorias','CategoriasController@show')->name('categoria.show');
    Route::post('/nova-categoria', 'CategoriasController@store')->name('categoria.store');
    Route::get('/mudar-status-categoria/{id}/{status}','CategoriasController@changeStatus')->name('categoria.change');
    Route::get('/remover-categoria/{id}/','CategoriasController@softDelete')->name('categoria.delete');

    //CLIENTES
    Route::get('/clientes', ['as' => 'clientes.showAll','uses' =>'ClientesController@showAll']);
    Route::get('/novo-cliente', ['as' => 'clientes.create','uses' =>'ClientesController@create']);
    Route::post('/cadastrar-cliente', ['as' => 'clientes.store','uses' =>'ClientesController@store']);
    Route::get('/editar-cliente/{id}', ['as' => 'clientes.edit','uses' =>'ClientesController@edit']);
    Route::put('/editar-cadastro-cliente/{id}', ['as' => 'clientes.update','uses' =>'ClientesController@update']);

    //FORMAS DE PAGAMENTO
    Route::get('/formas-de-pagamento','FormasPagamentoController@show')->name('formas.show');
    Route::post('/nova-formas-de-pagamento', 'FormasPagamentoController@store')->name('formas.store');
    Route::get('/mudar-status-formas-de-pagamento/{id}/{status}','FormasPagamentoController@changeStatus')->name('formas.change');

    //PEDIDO
    Route::get('/novo-pedido','PedidosController@create')->name('pedido.create');
    Route::post('/adicionar-item-pedido', 'PedidosController@addToCart')->name('pedido.addItem');
    Route::post('/salvar-pedido', 'PedidosController@store')->name('pedido.store');
    Route::post('/remover-item-pedido', 'PedidosController@removeItemPedido')->name('carrinho.remove');
    Route::get('/pedidos', 'PedidosController@showAll')->name('pedido.showAll');

    //PRODUTOS
    Route::get('/produtos','ProdutosController@showAll')->name('produto.showAll');
    Route::get('/novo-produto', 'ProdutosController@create')->name('produto.create');
    Route::post('/cadastrar-produto', 'ProdutosController@store')->name('produto.store');
    Route::get('/editar-produto/{id}','ProdutosController@edit')->name('produto.edit');
    Route::put('/editar-cadastro-produto/{id}','ProdutosController@update')->name('produto.update');
    Route::post('/ajax-busca-produto-por-categoria','ProdutosController@findProdutosPorCategoriaAjax');

});

app/Models/Categoria.php
<?php

namespace Tcc\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use Tcc\Scopes\TenantModelsScope;

class Categoria extends Model implements Transformable
{
    use TransformableTrait, TenantModelsScope, SoftDeletes;

    protected $fillable = ['categoria', 'empresa_id','ativo'];

    protected $dates = ['deleted_at'];

    public function empresa()
    {
        return $this->belongsTo(Empresa::class);
    }


}

app/Http/Controllers/CategoriasController.php
<?php

namespace Tcc\Http\Controllers;

use Carbon\Carbon;
use Tcc\Http\Requests\CategoriaCreateRequest;
use Tcc\Models\Categoria;
use Tcc\Repositories\CategoriaRepository;

class CategoriasController extends Controller
{
    /** @var  CategoriaRepository */
    protected $repository;

    /**
     * CategoriasController constructor.
     * @param CategoriaRepository $repository
     */
    public function __construct(CategoriaRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show()
    {
        $categorias = $this->repository->all();

        return view('categorias.show', compact('categorias'));
    }


    /**
     * @param CategoriaCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CategoriaCreateRequest $request)
    {
        $this->repository->create($request->all());
        flash()->success('Categoria cadastrada com sucesso.');

        return back();
    }


    /**
     * @param int $id
     * @param int $status
     * @return \Illuminate\Http\RedirectResponse
     */
    public function changeStatus($id, $status)
    {
        $this->repository->update(['ativo' => $status], $id);
        flash()->success('Categoria alterada com sucesso.');

        return back();
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function softDelete($id)
    {
        $this->repository->delete($id);
        flash()->success('Categoria removida com sucesso.');

        return back();

    }
}

resources/views/categorias/_form.blade.php
<div class="col-md-12 form-group{{ $errors->has('categoria') ? 'has-error' : '' }}">
    <label for="name" class="">Categoria</label>
    {!! Form::text('categoria',null,['class' => 'form-control','required']) !!}
</div>

resources/views/categorias/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 ">
                <div class="panel panel-default">
                    <div class="panel-heading">Cadastrar Nova Categoria</div>
                    <div class="panel-body">
                        @include('errors._check_form')
                        @include('flash::message')
                        {!! Form::open(['route' => 'sistema.categoria.store', 'method' => 'post' ]) !!}
                        @include('categorias._form')

                        <div class="form-group">
                            <div class="col-md-3">
                                <button type="submit" class="btn btn-success">
                                    Cadastrar
                                </button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 ">
                <div class="panel panel-default">
                    <div class="panel-heading">Categorias</div>
                    <div class="panel-body">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Categoria</th>
                                <th>Ativo</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($categorias as $categoria)
                                <tr>
                                    <td>{{$categoria->id}}</td>
                                    <td>{{$categoria->categoria}}</td>
                                    <td>{{($categoria->ativo)? 'Sim': 'Não'}}</td>
                                    <td class="text-right">
                                        @if($categoria->ativo == 0)
                                            <a href="{{route('sistema.categoria.change',[$categoria->id,1])}}"
                                               class="btn btn-success btn-sm">
                                                Ativar
                                            </a>
                                        @else
                                            <a href="{{route('sistema.categoria.change',[$categoria->id,0])}}"
                                               class="btn btn-warning btn-sm">
                                                Desativar
                                            </a>
                                        @endif
                                            <a href="{{route('sistema.categoria.delete',[$categoria->id])}}"
                                               class="btn btn-danger btn-sm">
                                                Remover
                                            </a>
                                    </td>
                                </tr>
                            @empty
                                <tr class="text-center">
                                    <td colspan="4">Nenhum registro encontrado.</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection